// Example pages for the card: Nikita's four public WebGL side projects.
// image — poster (the first frame of the clip); video — looping preview, { webm?, mp4? }; glyph — inner SVG, viewBox 0 0 64 64.
window.SIDE_PROJECTS = [
  {
    id: 'windcrest',
    label: 'Side project 01',
    title: 'Windcrest',
    alt: 'The crest of a hill under a grey sky, grass bent by a strong wind',
    image: 'media/card-windcrest.webp',
    video: { mp4: 'media/card-windcrest.mp4' },
    kind: 'A field of grass in the wind',
    meta: 'three.js · GLSL · 2026',
    stats: [['380k', 'blades of grass'], ['7', 'vertices a blade'], ['5', 'ready-made looks']],
    points: [
      'The grass from the first screen of the portfolio as a demo of its own: 380,000 real blades in one instanced draw call.',
      'Wind comes in gusts, grass grows in tufts, and the cursor leaves a trail like a hand on a carpet, all in a vertex shader.',
      'A blade is never thinner than a pixel, so far grass does not shimmer. Everything is on a panel, and the link keeps the settings.',
    ],
    glyph: '<path d="M10 52h44"/><path d="M22 52c1-14 5-24 13-34"/><path d="M32 52c0-12 4-21 12-28"/><path d="M42 52c-1-10-5-18-13-24"/>',
    demo: 'https://kloserock97-tech.github.io/windcrest/',
    repo: 'https://github.com/kloserock97-tech/windcrest',
  },
  {
    id: 'driftfield',
    label: 'Side project 02',
    title: 'Driftfield',
    alt: 'A cloud of white particles torn into shreds by a flow field',
    image: 'media/card-driftfield.webp',
    video: { mp4: 'media/card-driftfield.mp4' },
    kind: 'A cloud that drifts like smoke',
    meta: 'three.js · GLSL · 2026',
    stats: [['80k', 'points'], ['0', 'stored frames'], ['~110 fps', 'on an integrated GPU']],
    points: [
      '80,000 points drift like smoke in a draught: a curl-noise field the GPU works out for every point in every frame.',
      'No frame depends on the one before, so time can stop and rewind like a video, and the shape holds.',
      'Background blur like a camera, with a real f-stop from the thin-lens formula. Everything is on a panel.',
    ],
    glyph: '<path d="M10 40c8-20 28-24 36-12 6 9-4 18-12 12-6-5-1-13 5-10"/><path d="M12 50c14 4 32 2 42-10"/><path d="M8 28c4-8 10-13 18-15"/>',
    demo: 'https://kloserock97-tech.github.io/driftfield/',
    repo: 'https://github.com/kloserock97-tech/driftfield',
  },
  {
    id: 'nightsail',
    label: 'Side project 03',
    title: 'Nightsail',
    alt: 'A giant marble head surfacing from a night sea under a column of light',
    image: 'media/card-nightsail.webp',
    video: { mp4: 'media/card-nightsail.mp4' },
    kind: 'A marble head in a night sea',
    meta: 'three.js · WebGPU · TSL · 2026',
    stats: [['1', 'light in the scene'], ['5,400', 'sparks in the core'], ['WebGPU', 'shaders in TSL']],
    points: [
      'A giant marble head under a column of light. The tide drowns it and gives it back.',
      'The stone knows the height of the same waves the sea draws, so the water touches it exactly; wet marble darkens and dries slowly.',
      'Built on WebGPU with shaders in TSL. Everything, even the tide, is on the panel and saved in the link.',
    ],
    glyph: '<path d="M32 8v10"/><circle cx="32" cy="29" r="10"/><path d="M8 44q6-6 12 0t12 0 12 0 12 0"/><path d="M8 53q6-6 12 0t12 0 12 0 12 0"/>',
    demo: 'https://kloserock97-tech.github.io/nightsail/',
    repo: 'https://github.com/kloserock97-tech/nightsail',
  },
  {
    id: 'meadow-walk',
    label: 'Side project 04',
    title: 'Meadow Walk',
    alt: 'Dark hills covered in dense grass under a low sun',
    image: 'media/card-meadow.webp',
    video: { mp4: 'media/card-meadow.mp4' },
    kind: 'A flight over a windy meadow',
    meta: 'React Three Fiber · GLSL · 2026',
    stats: [['500k', 'blades of grass'], ['1', 'height map a frame'], ['~75 fps', 'on an integrated GPU']],
    points: [
      'An endless flight over a windy meadow: half a million blades of grass bending in the wind.',
      'The cursor sends soft waves through the field; pebbles and dust ride the crest and settle back.',
      'Hills, grass and shadows take their height from one shared map that updates every frame.',
    ],
    glyph: '<path d="M6 50c8-16 16-18 24-6 7-18 18-20 28-2"/><path d="M6 50h52"/><circle cx="46" cy="18" r="5"/>',
    demo: 'https://kloserock97-tech.github.io/meadow-walk/',
    repo: 'https://github.com/kloserock97-tech/meadow-walk',
  },
];
